name = "Poptart"
uuid = "197b51f5-fdb5-5f35-aa9f-0a14f35f5b28"
keywords = ["GUI"]
license = "MIT"
desc = "GUI programming in Julia based on CImGui.jl"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.2.0"

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
