name = "Poptart"
uuid = "197b51f5-fdb5-5f35-aa9f-0a14f35f5b28"
keywords = ["GUI"]
license = "MIT"
desc = "GUI programming in Julia based on CImGui.jl"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>", "Zhang Shitian https://github.com/Eggiverse"]
version = "0.4.0"

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
ImGuiGLFWBackend = "623d79b3-9695-4e60-bd7e-2a5aabaa6933"
ImGuiOpenGLBackend = "9d0819b4-44e7-43a2-ad03-8fb999128168"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
CImGui = "1.82"
ImGuiGLFWBackend = "0.1"
ImGuiOpenGLBackend = "0.1"
ColorTypes = "0.10, 0.11"
Colors = "0.12"
FixedPointNumbers = "0.8"
Jive = "0.2"
UnicodePlots = "1.3, 2.11"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
