name = "Poptart"
uuid = "197b51f5-fdb5-5f35-aa9f-0a14f35f5b28"
keywords = ["GUI"]
license = "MIT"
desc = "GUI programming in Julia based on Nuklear.jl"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.1"

[deps]
Nuklear = "8d0e9305-38f4-5c97-8ceb-e1429a1a2d0c"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
